---
title: "Google & Debugging Practice"
author: "Sam Csik"
date: "9/15/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries (we'll be using the `penguins` dataset from the `palmerpenrguins` package)
```{r}
#################################
# load packages
#################################

library(tidyverse)
library(palmerpenguins)
```

# Problem 1.1: Starting simple -- think about list of easy things to check for
```{r}
adelie_only <- penguins %>% 
  fiter(species = "adelie")

adelie_only <- penguins %>% 
  filter(species == "Adelie")
```

# Problem 1.2: Starting simple -- running line-by-line until you encounter the problem
```{r}

```

```{r}
# Source: https://www.rebeccabarter.com/blog/2019-08-19_purrr/ 

# create function that adds 10 to whatever value is supplied
addTen <- function(y){
  return(y + 10)
}

# .x = a list or atomic vector; .f = a function, formula, or vector
my_new_data <- map(.x = c(1, 4, 7), 
                   .f = addTen)

# create vector of ordinals (OR if you have the {english} package installed, you can use the following code:
  # `ordinals <- english:ordinal(1:3)`
ordinals <- c("first", "second", "third")

for (i in 1:length(my_new_data)){
  calculated_value <- my_new_data[i]
  #calculated_value <- calculated_value[[1]]
  #print(paste("The", ordinals[i], "calculated value is:", calculated_value))
  message("The ", ordinals[i], " calculated value is: ", calculated_value)
}

```

# sorting blue animals
```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ vector of animals  ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~

animals <- c("blue tang", "red panda", "Blue jay",
             "green sea turtle", "blue morpho butterfly", 
             "Blue iguana", "Red squirrel")

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ initialize empty list to store blue-colored animals  ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

blue_animals <- c()

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ sort blue animals into their own list  ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

for (i in 1:length(animals)){
  
  current_animal <- animals[i]
  
  if(isTRUE(str_detect(current_animal, "(?i)blue"))){
    
    message("The '", current_animal, "' is a blue animal")
    # blue_animals <- current_animal
    blue_animals <- append(blue_animals, current_animal)
    
  }
  
}

```

# ggplot example
```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ load libraries  ----
##~~~~~~~~~~~~~~~~~~~~~~~~

library(tidyverse)
library(palmerpenguins)

##~~~~~~~~~~~~~~~~~~~~~~~
##  ~ plot raw data  ----
##~~~~~~~~~~~~~~~~~~~~~~~

x<- ggplot(data = na.omit(penguins), aes(x = species, y = body_mass_g, shape = sex)) +
  geom_point(alpha = 0.2, position = position_jitterdodge(dodge.width = 0.8)) + 
  
  ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##  ~ calculate & layer on summary stats (mean +/- sd)  ----
  ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # means
  stat_summary(mapping = aes(color = species),
               fun = "mean", geom = "point", size = 4,
               position = position_dodge(width = 0.8)) +
  
  # standard deviations
  stat_summary(mapping = aes(color = species),
               fun = "mean", geom = "errorbar", size = 1, width = 0.2,
               fun.max = function(x) mean(x) + sd(x),
               fun.min = function(x) mean(x) - sd(x),
               position = position_dodge(width = 0.8)) +
  
  ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##  ~ manually adjust colors & shapes  ----
  ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  scale_color_manual(values = c("#FF8C02", "#A93FF1", "#148F90"), name = "Species") + 
  scale_shape_manual(values = c(15, 16), name = "Sex") + 
  
  # add nicer axis labels + title + caption
  labs(x = "Penguin Species", 
       y = "Body Mass (g)",
       title = "Body mass of female vs. male adelie, chinstrap, and gentoo penguins",
       subtitle = "Colored points represent mean body mass (± SD)",
       caption = "Data Source: Dr. Kristen Gorman, LTER Palmer Station") +
  
  ##~~~~~~~~~~~~~~~~~~~~
  ##  ~ edit theme  ----
  ##~~~~~~~~~~~~~~~~~~~~
 
  theme_classic() + 
  theme(
    
        # text
        plot.title = element_text(hjust = 0, size = 14),
        axis.text = element_text(color = "black", size = 10),
        axis.title = element_text(color = "black", size = 14),
        plot.caption = element_text(size = 7, hjust = 1, color = "gray", face = "italic"),

        # plot
        panel.border = element_rect(color = "black", size = 0.7, fill = NA))

cowplot::save_plot(here::here("media", "penguin_plot.png"), x, base_width = 7, base_height = 6)
```

# ggplot example
```{r}
##~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ load libraries  ----
##~~~~~~~~~~~~~~~~~~~~~~~~

library(tidyverse)
library(palmerpenguins)

##~~~~~~~~~~~~~~~~~~~~~~~
##  ~ plot raw data  ----
##~~~~~~~~~~~~~~~~~~~~~~~

ggplot(data = na.omit(penguins), aes(x = species, y = body_mass_g, shape = sex)) +
  geom_point(alpha = 0.2, position = position_jitterdodge(dodge.width = 0.8)) + 
  
  ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##  ~ calculate & layer on summary stats (mean +/- sd)  ----
  ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # means
  stat_summary(mapping = aes(color = species),
               fun = "mean", geom = "point", size = 4) +
               #position = position_dodge(width = 0.8)) +
  
  # standard deviations
  stat_summary(mapping = aes(color = species),
               fun = "mean", geom = "errorbar", size = 1, width = 0.2,
               fun.max = function(x) mean(x) + sd(x),
               fun.min = function(x) mean(x) - sd(x)) +
               #position = position_dodge(width = 0.8)) +
  
  ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##  ~ manually adjust colors & shapes  ----
  ##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  scale_color_manual(values = c("#FF8C02", "#A93FF1", "#148F90"), name = "Species") + 
  scale_shape_manual(values = c(15, 16), name = "Sex") +
  
  # add nicer axis labels + title + caption
  labs(x = "Penguin Species", 
       y = "Body Mass (g)",
       title = "Body mass of female vs. male adelie, chinstrap, and gentoo penguins",
       subtitle = "Colored points represent mean body mass (± SD)",
       caption = "Data Source: Dr. Kristen Gorman, LTER Palmer Station") +
  
  ##~~~~~~~~~~~~~~~~~~~~
  ##  ~ edit theme  ----
  ##~~~~~~~~~~~~~~~~~~~~
 
  theme_classic() + 
  theme(
    
        # text
        plot.title = element_text(hjust = 0, size = 14),
        axis.text = element_text(color = "black", size = 10),
        axis.title = element_text(color = "black", size = 14),
        plot.caption = element_text(size = 7, hjust = 1, color = "gray", face = "italic"),

        # plot
        panel.border = element_rect(color = "black", size = 0.7, fill = NA))

```

